### ISSUE TITLE
EPIPE error on windows

### ISSUE THREAD

**Issue by mendrik** [jjwilly16/node-pdftk#23]
**Describe the bug**
So I followed the examples quite thoroughly. However the .output() call fails with the following exception:
```
(node:21488) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at Socket._writeGeneric (net.js:768:25)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at _Promise ([...]\node_modules\node-pdftk\index.js:360:33)
```
it's thrown from the line `child.stdin.write(this.stdin);`

any ideas what could be causing it?

**Comment by mendrik** [comment]
Ok I found the cause, I think the pdftk bin entry doesn't default to 'pdktk', once I used .config() it started to work.
